### ISSUE TITLE
"cd .." doesn't fulfill its purpose

### ISSUE THREAD

**Issue by lokeshmohanty** [sr6033/lterm#13]
"you will get something like -> /home/lterm/ since you were on /home/lterm/Documents
Type cd ~ to continue
Type exit to exit cd command and then cat hello.txt to continue."
This is displayed but the directory isn't changed.

**Comment by lokeshmohanty** [comment]
same with cd ~. It also doesn't change the directory. This is what it shows "Type cd .. to continue
Type exit to exit cd command and then cat hello.txt to continue.". And on following its instructions it gives this "you will get something like -> /home/lterm/ since you were on /home/lterm/Documents
Type cd ~ to continue
Type exit to exit cd command and then cat hello.txt to continue"

**Comment by sr6033** [comment]
Yes. The directory change hasn't been added yet. If you can add it then send in a **PR**. Till now, it just text for `cd..` and `cd~`.

**Comment by lokeshmohanty** [comment]
I have added a PR. That should solve this.
