### ISSUE TITLE
Need help with adding commands.

### ISSUE THREAD

**Issue by shivhek25** [sr6033/lterm#22]
I wanted to add the more and less commands. As we know, these commands require access to a file which will shown partially or be scrollable. How do I go about accessing the file using the code for these commands ?

**Comment by sr6033** [comment]
You can create a virtual file. @lokesh1197  has already created a system for directory. Check that out to get an idea.

**Comment by shivhek25** [comment]
Thank you. 
Also, could you tell me how do I check my changes locally ? A blank tab opens up when I execute index.html. @sr6033

**Comment by sr6033** [comment]
Keep connected to the internet because the `CSS` and `JS` files are in CDN format.

**Comment by lokeshmohanty** [comment]
The of object stores virtual files data as a string.

**Comment by shivhek25** [comment]
Staying connected to the internet didn't work. Tried running on chrome as well. Still a blank tab. @sr6033

**Comment by sr6033** [comment]
May be, you didn't clone it properly. I checked it. It is opening up locally.
