### ISSUE TITLE
Clear remains Not completed

### ISSUE THREAD

**Issue by SubhrajitPrusty** [sr6033/lterm#6]
Clear command shows "Not Completed" even after completion of all commands.

**Comment by sr6033** [comment]
I will check it out. The issue is occurring due to a recent merge by another fellow.

**Comment by shivhek25** [comment]
PR#23 opened which fixes this issue @sr6033

**Comment by sr6033** [comment]
Reverted it. Not working.

**Comment by bluez-sh** [comment]
@sr6033 fixed it in PR #31
